# Gmail SMTP settings
smtp.host=smtp.gmail.com
smtp.port=587
smtp.auth=true
smtp.starttls=true

# Paste your Gmail account and app password below
smtp.user=dnyaneshadkar@gmail.com
smtp.pass=dicdmjqmfqyjjwjf
